# Generated by Django 2.2.12 on 2020-11-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='order_queue',
            field=models.IntegerField(default=0),
        ),
    ]
